import type { Workplace, EmployerWorkerContract } from "../api/employer/types";

export const DUMMY_WORKPLACES: Workplace[] = [
  { id: 1, businessName: "맥도날드", name: "맥도날드 nn점", workerCount: 12, isActive: true },
  { id: 2, businessName: "스타벅스", name: "스타벅스 n점", workerCount: 5, isActive: true },
];

export const DUMMY_WORKERS: EmployerWorkerContract[] = [
  {
    contractId: 1,
    workerId: 101,
    workerName: "홍길동",
    workDaysSummary: ["월", "수", "금"],
    hourlyWage: 10300,
    paymentDay: 1,
    fourMajorInsurance: true,
    incomeTax: false,
    workSchedules: [
      {
        key: "1-1",
        day: "일요일",
        startHour: "10",
        startMinute: "00",
        endHour: "16",
        endMinute: "00",
        breakMinutes: 0,
      },
      {
        key: "1-2",
        day: "화요일",
        startHour: "10",
        startMinute: "00",
        endHour: "16",
        endMinute: "00",
        breakMinutes: 0,
      },
    ],
    contractStartDate: "2025-01-01",
    isActive: true,
  },
  {
    contractId: 2,
    workerId: 102,
    workerName: "호날두",
    workDaysSummary: ["화", "목"],
    hourlyWage: 12000,
    paymentDay: 5,
    fourMajorInsurance: true,
    incomeTax: true,
    workSchedules: [
      {
        key: "2-1",
        day: "화요일",
        startHour: "09",
        startMinute: "00",
        endHour: "18",
        endMinute: "00",
        breakMinutes: 0,
      },
      {
        key: "2-2",
        day: "목요일",
        startHour: "09",
        startMinute: "00",
        endHour: "18",
        endMinute: "00",
        breakMinutes: 0,
      },
    ],
    contractStartDate: "2025-03-15",
    isActive: true,
  },
  {
    contractId: 3,
    workerId: 103,
    workerName: "메시",
    workDaysSummary: ["월", "화", "수", "목", "금"],
    hourlyWage: 10300,
    paymentDay: 10,
    fourMajorInsurance: false,
    incomeTax: true,
    workSchedules: [
      {
        key: "3-1",
        day: "월요일",
        startHour: "08",
        startMinute: "00",
        endHour: "12",
        endMinute: "00",
        breakMinutes: 0,
      },
      {
        key: "3-2",
        day: "수요일",
        startHour: "08",
        startMinute: "00",
        endHour: "12",
        endMinute: "00",
        breakMinutes: 0,
      },
      {
        key: "3-3",
        day: "금요일",
        startHour: "08",
        startMinute: "00",
        endHour: "12",
        endMinute: "00",
        breakMinutes: 0,
      },
    ],
    contractStartDate: "2024-09-01",
    isActive: true,
  },
  {
    contractId: 4,
    workerId: 104,
    workerName: "하피나",
    workDaysSummary: ["토", "일"],
    hourlyWage: 11000,
    paymentDay: 25,
    fourMajorInsurance: false,
    incomeTax: false,
    workSchedules: [
      {
        key: "4-1",
        day: "토요일",
        startHour: "12",
        startMinute: "00",
        endHour: "22",
        endMinute: "00",
        breakMinutes: 0,
      },
      {
        key: "4-2",
        day: "일요일",
        startHour: "12",
        startMinute: "00",
        endHour: "22",
        endMinute: "00",
        breakMinutes: 0,
      },
    ],
    contractStartDate: "2025-06-01",
    isActive: true,
  },
];
